config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :user_crud
  resources :category_list
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  root to: 'service_centers#index'
  resources :service_centers do
    collection do
      get 'shop_detail', to: 'service_centers#shop_detail'
      get 'admin', to: 'service_centers#admin'    
      get 'all_shop', to: "service_centers#all_shop"
      get 'shop_list', to: "service_centers#shop_list"
      post "order_pending", to: "service_centers#order_pending"
    end    
    member do
      get 'show_data', to: "service_centers#show_data"
      get 'update_to', to: "service_centers#update_to"
    end
  end
  get 'order/:id/:service_id',to: "clients#order_cancel",as: :order_cancel
  get 'client_request/:id', to: 'service_centers#client_request',as: :client_request
  get 'add_service/:id', to: 'service_centers#add_service', as: :add_service
  get 'request_to_owner/:id', to:'service_centers#request_to_owner',as: :request_to_owner
  post 'order_confirmation/:data/' , to: 'service_centers#order_confirmation',as: :order_confirmation
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  get 'payment/:client_id/:cost/:service_center_id', to: 'service_centers#payment', as: 'payment'
  post 'charge', to: 'service_centers#charge', as: 'charge'
  # root "articles#index"
  resources :clients do
    collection do  
      get "user_profile",to: 'clients#user_profile'
      get "admin_path" ,to: "clients#admin"
    end    
    member do 
      get "show_data", to: "clients#show_data"
      get "update_slot", to: "clients#update_slot"
      get "bill_detail", to: "clients#bill_detail"
      get 'revenue',to: "clients#revenue"
    end  

  end
  resources :slot ,except: %i[create edit destroy]
  post 'create/:id', to: 'slot#create'
  get 'edit/:service_id/:slot_id',to: 'slot#edit' ,as: :edit_slot
  get 'delete/:service_id/:slot_id',to: 'slot#edit' ,as: :delete_slot
end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_action :authenticate_user!
    include Vehicle
    def index
    end     


    def order_cancel
        @client = Client.find(params[:id])
        @service = ServiceCenter.find(params[:service_id])
        @user = User.find(@client.user_id)
        UserMailer.with(email: @user.email,service:@service).order_cancel_mail.deliver_later
    end 

    def show_data
        @d = Client.find(params[:id])
        @data  = CategoryList.find_by(name:@d.category)
        @u = User.find(@d.user_id)
    end
    def show
        @client = client_info(params[:id])
    end

    
    def create
        @admin = CategoryList.new(client_params)
        @admin.save
    end
    def update_slot
        a = Slot.find(params[:id])
        s = Client.where(confirm_slot:a.name)
        if a.status == "booked"
            a.update(status:"available") 
            s.update(status:"not booked")
            redirect_to user_profile_clients_path
        else
            flash[:msg] = "invalid"
            redirect_to user_profile_clients_path
        end    

    end

    def bill_detail
        @bill = Payment.find_by(client_id:params[:id])
        @data = 0
        if @bill.present?
            @data = Client.find(params[:id])
        end 
           
    end

    def user_profile
        if current_user.user_rule == "shop owner" 
            @shop_owner = shop_info(current_user.id)
        elsif current_user.user_rule =="client"
            redirect_to client_path(current_user.id)
        else
            redirect_to admin_path_clients_path
        end            
    end    

    def revenue
        @shop = Payment.where(service_center_id:params[:id])
        @total = 0
        @shop.each do |i|
            @total = @total+i.amount
        end    
    end    


    private
    def client_params
        params.require(:category_list).permit(:name,:cost,:time)
    end    

   
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/admin.html.erb
<div class="container text-center">
              
   <h1>  admin Dashboard</h1>
   <%=link_to "User_list",user_crud_index_path,class:"btn btn-danger"%>
   <%=link_to "category_list",'/category_list',class:"btn btn-danger"%>

   <%=link_to "Service Center", all_shop_service_centers_path,class:"btn btn-danger"%>
   

 



</div>

app/views/clients/bill_detail.html.erb
<h1>Bill Detail</h1>
 <div class="bg">

  <div class="table-wrapper">
    <table class="fl-table">
      <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">vehicle_number</th>
              <th scope="col">Contact number</th>
              <th scope="col">cost</th>
              <th scope="col">Request Date</th>
              <th scope="col">Request_time</th>
              <th scope="col">Cofirm date</th>
              <th scope="col">Cofirm Time</th>
              <th scope="col">Slot number</th>
              <th scope="col">Category</th>
              <th scope="col">Next service date</th>
            </tr>
          </thead>
          <tbody>
              <tr>
                  <%if @data == 0%>
                  Please pay first
                  <%else%>

                  <td>
                    <%=@data.name%>
                  </td>
                  <td>
                    <%=@data.vehicle_number%>
                  </td>
                  <td>
                    <%=@data.contact_number%>
                  </td>
                  <td>
                    <%=@data.cost%>
                  </td>
               
                 
                  <td>
                    <%=@data.request_date%>
                  </td>
                  <td>
                    <%=@data.request_time%>
                  </td>
                  <td>
                    <%=@data.confirm_date%>
                  </td>
                  <td>
                    <%=@data.confirm_time%>
                  </td>
                  <td>
                    <%=@data.confirm_slot%>
                  </td>
                  <td>
                    <%=@data.category%>
                  </td>
                  <td>
                    <%=@data.next_date%>
                  </td>
                  

                  <%end%>
              </tr> 
              
          </tbody>
        </table>

      </div>
   
 </div>

app/views/clients/index.html.erb
fghjkl

app/views/clients/revenue.html.erb
<%= "Total  = #{@total}"%>

app/views/clients/show.html.erb
 <div class="bg">

  <h2>User Table</h2>
  
  
  <div class="table-wrapper">
      <table class="fl-table">
        <thead >
          <tr>
            <th scope="col">Name</th>
            <th scope="col">vehicle_number</th>
            <th scope="col">Contact number</th>
            <th scope="col">cost</th>
            <th scope="col">service_center_id</th>
            <th scope="col">User_id</th>
            <th scope="col">Request Date</th>
            <th scope="col">Request_time</th>
            <th scope="col">Cofirm date</th>
            <th scope="col">Cofirm Time</th>
            <th scope="col">Slot number</th>
            <th scope="col">Category</th>
            <th scope="col">Next service date</th>  
            <th scope="col">Bill</th>
            <th scope="col">Payment</th>
          </tr>
        </thead>
          <tbody>
            <%@client.each do |i|%>
            <%a = Client.find(i)%>
           <tr>
             <td> <%=a.name%></td>
             <td> <%=a.vehicle_number%></td>
             <td><%=a.contact_number%></td>
             <td> <%=a.cost%></td>
             <td> <%=a.service_center_id%></td>
             <td> <%=a.user_id%></td>
             <td><%=a.request_date%></td>
             <td> <%=a.request_time%></td>
             <td> <%=a.confirm_date%></td>
             <td><%=a.confirm_time%></td>
             <td><%=a.confirm_slot%></td>
             <td> <%=a.category%></td>
             <td><%=a.next_date%></td>
             <td><%=link_to "Bill",bill_detail_client_path(a.id)%></td>
             <td> <% if a.confirm_date%>
               <%= link_to "payment",payment_path(a.id,a.cost,a.service_center_id )%>
              <%end%>   </td>
           </tr>
           <%end%>
         </tbody>
      </table>
  </div>
  
    </div>

app/views/clients/show_data.html.erb
<div class="container">
    <%= form_with method: :get,model:@d,url: service_center_path do |form| %>
    <div> 
      <%= form.label :Your_Name %><br>
      <%= form.text_field :name %>
    </div>
      
    <div> 
        <%= form.label :email %><br>
        <%= form.text_field :email, value: @u.email %>
    </div>


    <div> 
      <%= form.label :time %><br>
      <%= form.text_field :name, value: @data.cost %>
    </div>
    
  
    <div>
        <%= form.label :Contact %><br>
        <%= form.text_field :contact_number %>
      </div>
    
      <div>
        <%= form.label :Vehicle_number %><br>
        <%= form.text_field :vehicle_number %>
      </div>
      
      <div>
        <%= form.label :status %><br>
        <%= form.text_field :status %>
      </div>
    
      <div>
        <%= form.label :Request_date%><br>
        <%= form.text_field :request_date %>
      </div>

      <div>
        <%= form.label :Category%><br>
        <%= form.text_field :category %>
      </div>
      <div>
        <%= form.label :Time_will_service_take%><br>
        <%= form.text_field :name, value: @data.time %>
      </div>

      <div>
        <%= form.label :Request_time%><br>
        <%= form.text_field :request_time %>
      </div>
    
      <div>
        <%= form.label :confirm_date%><br>
        <%= form.text_field :confirm_date %>
      </div>
    
      <div>
        <%= form.label :confirm_time%><br>
        <%= form.text_field :confirm_time %>
      </div>
    
    
    <div>
      <%= form.submit "submit"%>
    </div>
    <% end %> 
    
    


</div>

app/views/clients/user_profile.html.erb
<%= flash[:msg]%>
<% if @shop_owner%>
<%@shop_owner.each do |i|%>
<header>
  <h2>  <p style="margin-right: 822px;"> slots</p>
  <% a = ServiceCenter.find(i.id)%>
  <% a.slots.all.each do |j|%>
   <div class="row container">
               <div class=" text-center  col-3">
                <%=j.name%> 
                <br>
               </div>

               <div class="col-7 text-center">
                
                <%=j.status%> <%=link_to "Release slot",update_slot_client_path(j.id)%><br>
              </div>
   </div>

  <%end%></h2>
</header>

<section>
 
  <nav>
    <ul class="add row">
       <div class="col-6">
          Name <br>
          Shop name<br>
          Location  <br>
          Address<br>
       </div>
       <div class="col-6">
        <%= i.shop_owner%> <br>
        <%= i.shop_name%>  <br>
        <%= i.location%>  <br>
        <%= i.address%>  <br>
        <%= link_to "Revenue",revenue_client_path(i.id)%>
       </div>
    </ul>
  </nav>
  
  <article class="add">
    <h2 style="color:black; margin-right:1050px;">Category</h2>
    <% a = ServiceType.where(service_center_id:i.id)%>
    <% a.each do |t|%>
      <div class="row">
        <div class=" text-center  col-3">
          Type of services: <br>
          Cost of service:
          <br>
         </div>
    
         <div class="col-7 text-center">
          
          <%= t.name%> <br>
         <%=t.cost%>
        </div>
      </div>
 
    
    <br>
  <%end%>

    
  </article>
</section>

<footer>
  <%=link_to "all _request" , request_to_owner_path(i.id) ,class:"btn text-white"%>
</footer>
<%end%>
  <%else%>
    ftgyhjk
  <%end%>