config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :user_crud
  resources :category_list
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  root to: 'service_centers#index'
  resources :service_centers do
    collection do
      get 'shop_detail', to: 'service_centers#shop_detail'
      get 'admin', to: 'service_centers#admin'    
      get 'all_shop', to: "service_centers#all_shop"
      get 'shop_list', to: "service_centers#shop_list"
      post "order_pending", to: "service_centers#order_pending"
    end    
    member do
      get 'show_data', to: "service_centers#show_data"
      get 'update_to', to: "service_centers#update_to"
    end
  end
  get 'order/:id/:service_id',to: "clients#order_cancel",as: :order_cancel
  get 'client_request/:id', to: 'service_centers#client_request',as: :client_request
  get 'add_service/:id', to: 'service_centers#add_service', as: :add_service
  get 'request_to_owner/:id', to:'service_centers#request_to_owner',as: :request_to_owner
  post 'order_confirmation/:data/' , to: 'service_centers#order_confirmation',as: :order_confirmation
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  get 'payment/:client_id/:cost/:service_center_id', to: 'service_centers#payment', as: 'payment'
  post 'charge', to: 'service_centers#charge', as: 'charge'
  # root "articles#index"
  resources :clients do
    collection do  
      get "user_profile",to: 'clients#user_profile'
      get "admin_path" ,to: "clients#admin"
    end    
    member do 
      get "show_data", to: "clients#show_data"
      get "update_slot", to: "clients#update_slot"
      get "bill_detail", to: "clients#bill_detail"
      get 'revenue',to: "clients#revenue"
    end  

  end
  resources :slot ,except: %i[create edit destroy]
  post 'create/:id', to: 'slot#create'
  get 'edit/:service_id/:slot_id',to: 'slot#edit' ,as: :edit_slot
  get 'delete/:service_id/:slot_id',to: 'slot#edit' ,as: :delete_slot
end

app/models/service_center.rb
# frozen_string_literal: true

class ServiceCenter < ApplicationRecord
  belongs_to :user
  has_many :service_types, dependent: :destroy
  has_many :slots, dependent: :destroy
  has_many :clients, dependent: :destroy
  has_one_attached :image 
  

  validates :shop_owner, presence: true
  validates :shop_name, presence: true
  validates :location , presence:true
  validates :address , presence:true
end

app/controllers/service_centers_controller.rb
class ServiceCentersController < ApplicationController
  load_and_authorize_resource except: %i[index client_request your_profile client_profile order_confirmation charge payment create] 
  before_action :authenticate_user!, except: %i[index]
  include Vehicle
  

  def index
    @all = ServiceCenter.all
    @q = ServiceCenter.ransack(params[:q])
    @address = @q.result(distinct: true)
  end
  
  def all_shop
    @all = ServiceCenter.all
  end  

  def show_data
    @a = ServiceCenter.find(params[:id])
  end  
  def shop_list

  end   
   
  def order_pending
    @a = ServiceCenter.find(params[:client][:service_center_id])
    begin
      Shop::OrderService.new().pending_order_for_date(params)
    rescue =>e
      flash[:msg] = e
      redirect_to request_to_owner_path(@a)
    end    
  end  

  def edit
    @edit = ServiceCenter.find(params[:id])
  end 

  def update
    @service_center = ServiceCenter.find(params[:id])
    @service_center.update(service_params)
  end  


  def destroy
    @destroy = ServiceCenter.find(params[:id])
    @destroy.destroy
    flash[:msg] = "deleted successfully"
    redirect_to all_shop_service_centers_path
  end 



  def order_confirmation
    authorize! :update, ServiceCenter
    
    Shop::OrderService.new().order_confirmation(params)
  end  

  def admin 
  end


  def request_to_owner
    @service_center_id = ServiceCenter.find(params[:id])
    service_center_id = @service_center_id.slots.where(status:"available")
    @data = Client.where(service_center_id:params[:id])
  end  
  
  def create
    @service = ServiceCenter.new(service_params)
    @service.user = current_user
    unless @service.save
      render :new, status: :unprocessable_entity
    else
      redirect_to shop_detail_service_centers_path 
    end
  end   


  def new
    @service_center = ServiceCenter.new
  end


 
  def show
    @request_id = ServiceCenter.find(params[:id])
    begin 
      year = params[:request_date][2,2].to_i
      year1 = Time.now.strftime("%y").to_i
      y = year
      y1 = year1+1
      m = params[:request_date].split("-")[1].to_i
      m1 = Time.now.strftime("%m").to_i
      if year == year1
        if m>=m1
          Shop::OrderService.new().request(params,current_user.id)
        else
          flash[:e] = "invalid date"
          redirect_to client_request_path(@request_id)
        end    
      else
        raise "Please fill valid date"
      end    
    rescue => e
      flash[:error] = e
      redirect_to client_request_path(@request_id)
    end    
  end


  def add_service
    begin 
      Shop::OrderService.new().get_association(params)
      flash[:n] = 'Your are added the category succesfully'
      redirect_to shop_detail_service_centers_path
    rescue => e
      flash[:n] = e
      redirect_to shop_detail_service_centers_path
    end    
  end

  def shop_detail
    @shop = shop_info(current_user.id)
    @category = CategoryList.all
  end

  def client_request 
    @request_id = ServiceCenter.find(params[:id])
    @a = @request_id.service_types.pluck(:name)
    @time = Client.where(service_center_id:@request_id)
    @slots  = Slot.where(service_center_id:params[:id])
  end
  
  
  def charge
    flash[:alert] = Shop::OrderService.new().payment_gate_way(params,current_user) ? "bill charged successfully" : "some error occoured" 
    @payment = Payment.new(user_id: current_user.id, service_center_id: params[:service_center_id], client_id: params[:id],amount: params[:cost])
    @payment.save
    redirect_to root_path
  end

  def payment 
  end

  private
  def service_params
    params.require(:service_center).permit(:shop_name, :shop_owner, :location, :address,:image)
  end
end

app/controllers/servicecenters_controller.rb
# frozen_string_literal: true

# sasas

# Some documentation for Person
class ServicecentersController < ApplicationController
  before_action :authenticate_user!, only: %i[new shop_detail]
  include Vehicle

  def index
    @all = ServiceCenter.all
  end

  def create
    @service = ServiceCenter.new(service_params)
    @service.user = current_user
    redirect_to shop_detail_servicecenters_path if @service.save
  end

  def new
    @a = ServiceCenter.new
  end

  def service_type
    @id = params[:id]
  end

  def add_service
    get_association(params[:id], params[:service_name], params[:service_cost])
    flash[:n] = 'add succesfully'
  end

  def shop_detail
    @shop = shop_info(current_user.id)
  end

  def profile
    if current_user
      @profile = shop_info(current_user.id)
    else
      redirect_to root_path
    end
  end

  private

  def service_params
    params.require(:service_center).permit(:shop_name, :shop_owner, :location, :address)
  end
end

app/helpers/servicecenters_helper.rb
# frozen_string_literal: true

module ServicecentersHelper
end

app/views/service_centers/_servicetype.turbo_stream.erb
<turbo-stream action='after' target='dom1'>
    <template>
    <label for="service">Service</label><br>
    <input type="text" name="sevice" id="sevice"><br>
    </template>
</turbo-stream>

app/views/service_centers/add_service.html.erb
<h1>Here you can see full detail of your shop</h1>

app/views/service_centers/all_shop.html.erb
<%=flash[:msg]%>
  

 
      
  <div class="bg">

    <h2>CREATE SERVICE CENTER <%= link_to 'CREATE SHOP',new_service_center_path, class: "btn btn-danger"%>
    
    
    <div class="table-wrapper">
        <table class="fl-table">
            <thead>
            <tr>
                <th>Shop OWner</th>
                <th>Shop name</th>
                <th>Location</th>
                <th>Address</th>
                <th>show</th>
                <th>edit</th>
                <th>Destroy</th>
                <th>Slot</th>
            </tr>
            </thead>
            <tbody>
        
              <%@all.each do |i|%>
            <tr>
                <td class="text-dark">  <%= i.shop_owner%></td>
                <td class="text-dark"> <%= i.shop_name%></td>
                <td class="text-dark"> <%= i.location%> </td>
                <td class="text-dark"><%= i.address%></td>
                <td><%=link_to "show",show_data_service_center_path(i.id),class:"btn btn-danger"%> </td>
                <td>        <%=link_to "edit",edit_service_center_path(i.id),class:"btn btn-danger"%> </td>
                <td>       <%= link_to "Destroy", service_center_path(i.id), data: { turbo_method: :delete,turbo_confirm: "Are you sure?"},class:"btn btn-danger" %></td>
                <td> <%=link_to "Slot",slot_path(i.id),class:"btn btn-danger"%> </td>
            </tr>
            <%end%>
           
            <tbody>
        </table>
    </div>
    
      </div>

app/views/service_centers/client_request.html.erb
<div class="alert alert-primary text-center" role="alert">
  <%= flash[:invalid] %>
  <%=flash[:error]%>
  <%=flash[:e]%>
</div>


<h1>Please fill below detail to Request for <%= @request_id.shop_name%> </h1>

       <div class="container add">
        <div class="row">
                   <div class="col-6">
                         <h1 style="margin-right: 723px;"> slots</h1>
                     <% if @slots %>
                        <% @slots.each do |i|%>
                          <%=i.name%>
                          <%=i.status%> <br>
                        <%end%>
                        <% else %>
                          There is nothing for to display
                     <%end%>
                   </div>

                   <div class="col-6">
                               Status hgh<br>
                               
                               <table class="table">
                                <thead class="thead-dark ">
                                  <tr>
                                    
                                    <th scope="col">Slot Status</th>
                                    <th scope="col">Category</th>
                                    <th scope="col">Time</th>
                                    
                                  </tr>
                                </thead>
                                <tbody>
                                  <% @time.ids.each do |i|%>
                                  <%a = Client.find(i)%>
                                  <tr>
                                    <%if a.status == "booked"%>
                                  
                                    <td><%=a.status%></td>
                                    <td> <%=a.category%></td>
                                    <td> <%=a.category_time%></td>
                                    <%end%> 
                                  </tr>
                                  <%end%>
                                </tbody>
                              </table>
                              
                          

                            </div>
                             
                  </div>
        </div>


       </div>


<div class="container add mt-5">


   <div class="row">
           <div class="col-5">

               
                <% if @request_id%>
                  <%= form_with method: :get,url: service_center_path(@request_id) do |form| %>
                  <div>
                    <%= form.label :Your_Name %><br>
                    <%= form.text_field :name %>
                  </div>
                  
                  <div>
                    <%= form.label :Vehicle_Number%><br>
                    <%= form.text_field :vehicle_number %>
                  </div>

                  <div>
                      <%= form.label :Contact_Number%><br>
                      <%= form.text_field :contact_number %>
                  </div>

                  <div>
                    <%= form.label :Date%><br>
                    <%= form.date_field :request_date %>
                  </div>

                  <div>
                    <%= form.label :Time%><br>
                    <%= form.time_field :request_time %>
                  </div>



                    <div class="bg-dander mb-2">
                      <%= form.label :Category%><br>
                      <%= form.select :category,@a%>
                  </div>
                  
                  <div>
                    <%= form.submit "submit"%>
                  </div>
                  <% end %> 
                  <%else%>
                   nothing have to display
                <%end%>

           </div>


           <div class="col-7 text-center">
            <table class="table table-striped">
              <thead>
                <tr>
        

                  <th scope="col">Category</th>
                  <th scope="col">Price</th>
                  <th scope="col">Time</th>

                </tr>
              </thead>
              <tbody>
                <%CategoryList.all.each do |i|%>
                <tr>
                
                  <td><%=i.name%> </td>
                  <td><%=i.cost%> </td>
                  <td><%=i.time%> </td>
                  
                   
                </tr>
                <%end%>

          
                
              </tbody>
            </table>
            

            
           </div>


   </div>
</div>



 

app/views/service_centers/edit.html.erb
<div class="container add mt-4">

    <%= form_with model:@edit do |form| %>
    <div>
        <%= form.label :shop_owner %><br>
        <%= form.text_field :shop_owner%>
      </div>
    <div>
      <%= form.label :Shop_name%><br>
      <%= form.text_field :shop_name %>
    </div>

    <div>
      <%= form.label :location %><br>
      <%= form.text_field :location %>
    </div>

    <div>
        <%= form.label :address %><br>
        <%= form.text_field :address %>
    </div>
  
    <div>
        <%= form.label :image %><br>
        <%= form.file_field :image %>
      </div>


    <div>
      <%= form.submit%>
    </div>
<% end %> 



 </div>

app/views/service_centers/index.html.erb
<div class="add home">
 <%=flash[:alert]%>
 
               <div class="row">
                            <div class="col-6">

                              <% if @address %>
                              <%@address.each do |i|%>
                              
                                Shop_name:<%= i.shop_name%>
                                <li class="cards_item">
                                  <div class="card">
                                    <div class="card_image"><%= image_tag i.image if i.image.attached?%>
</div>
                                    <div class="card_content">
                                      <h2 class="card_title">Shop_name :<%= i.shop_name%></h2>
                                      <p class="card_text">address :<%=i.address%></p>
                                       <%= link_to 'Resquest for services' ,client_request_path(i.id),class:"btn1 text-center"%>
                                    </div>
                                  </div>
                                </li>
                                <hr>
                                <%end%>
                            
                            
                              <%else%>
                               nothing have to display
                             <%end%>

                          


                            </div>

               </div>



</div>



</div>

app/views/service_centers/new.html.erb
    
  <div class="container col-lg-6 mx-lg-auto card shadow mt-5">
    <div >
      <h3 class="card-title text-center">CREATE SHOP</h3>
    </div>
    
    <%= form_with  model: @service_center do |form| %>
  
    <div>
      <%= form.label :shop_owner %><br>
      <%= form.text_field :shop_owner ,class: "form-control form-control-lg"%>
      <% @service&.errors&.full_messages_for(:shop_owner)&.each do |message| %>
        <div style="color: red;"><%= message %></div>
      <% end %>
    </div>
    
    <div>
      <%= form.label :shop_name %><br>
      <%= form.text_field :shop_name ,class: "form-control form-control-lg"%>
      <% @service&.errors&.full_messages_for(:shop_name)&.each do |message| %>
        <div style="color: red;"><%= message %></div>
      <% end %>
    </div> 

    <div>
      <%= form.label :location %><br>
      <%= form.text_field :location,class: "form-control form-control-lg" %>
      <% @service&.errors&.full_messages_for(:location)&.each do |message| %>
        <div style="color: red;"><%= message %></div>
      <% end %>
    </div> 
    
    <div>
      <%= form.label :address %><br>
      <%= form.text_field :address ,class: "form-control form-control-lg"%>
      <% @service&.errors&.full_messages_for(:address)&.each do |message| %>
        <div style="color: red;"><%= message %></div>
      <% end %>
    </div>  
    <div>
      <%= form.label :image %><br>
      <%= form.file_field :image ,class: "form-control form-control-lg"%>
    </div> 

    <div class="mt-3">
      <%= form.submit 'create shop'%>
    </div>
  <% end %> 

   </div>
  
 

app/views/service_centers/payment.html.erb
<section class="p-4 p-md-5" style="
    background-color :  #FF6D28;
  ">
  <div class="row d-flex justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-5">
      <div class="card rounded-3" style="width:120%;">
        <div class="card-body p-4" >
            <p class="fw-bold mb-4">Add your Card here</p>
            <%= form_with url: '/charge', method: :post  do |f| %>
            <div class="row mb-4">
              <h4 class="text-success">Amount &euro; <%= params[:cost]%></h4>
              <p><%=f.hidden_field :cost, value: params[:cost]%></p>
              <%=f.hidden_field :id, value: params[:client_id]%>
              <%=f.hidden_field :service_center_id, value: params[:service_center_id]%>
              <div class="col-7">
                <div class="form-outline">
                    <%=f.text_field :number, class: "form-control form-control-lg"%>
                    <%=f.label :number, "Card_number",class:"form-label"%>
                </div>
              </div>
              <div class="col-3">
                <div class="form-outline">
                    <%=f.text_field :exp_month, class: "form-control form-control-lg"%>
                  <%=f.label :exp_month, "Expire_month",class:"form-label"%>
                </div>
              </div>
              <div class="col-3">
                <div class="form-outline">
                    <%=f.text_field :exp_year, class: "form-control form-control-lg"%>
                  <%=f.label :exp_year, "Expire_year",class:"form-label"%>
                </div>
              </div>
              <div class="col-2">
                <div class="form-outline">
                    <%=f.text_field :cvc, class:"form-control form-control-lg"%>
                    <%=f.label :cvc, class: "form-label" %>
                </div>
              </div>
            
            </div>
            <%=f.submit "continue", class:"btn btn-info"%>
        </div>
      </div>
    </div>
  </div>
</section>
<%end%>

app/views/service_centers/request_to_owner.html.erb
<div class="container add"> 
  <%=flash[:msg]%>
  <%if @data%>

    <% @data.each do |i| %>
      <div class="row">
        <div class="col-3 shadow-lg p-3 mb-5 bg-body rounded col-4">
               <div class="row">
                         <div class="col-6">
                              Name: <br>
                              vehicle_number <br>
                              contact_number <br>
                              Categoty <br>
                              Status <br>
                              request_date <br>
                              request_time  
                         </div>     

                         <div class="col-6">
                          <%=i.name%> <br>
                          <%=i.vehicle_number%> <br>
                          <%=i.contact_number%> <br>
                          <%=i.category%> <br>
                          <%=i.status%> <br>
                          <%=i.request_date%> <br>
                          <%=i.request_time%> <br>
                          <%= button_to "confirm" ,order_confirmation_path(i), method: :post, class: 'btn-primary' %> 
                         </div>
                 
               </div>
        </div>
        <div class="col-1">

        </div>
        <div class="col-6 shadow-lg p-3 mb-5 bg-body rounded">
        

                  <%= form_with model:i ,method: :post,url:order_pending_service_centers_path do |form| %>
                   <div class="mt-3">
                    <%= form.label :name %><br>
                    <%= form.text_field :name , class: "form-control form-control-lg"%>
                  </div>

                  <div class="mt-2">
                    <%= form.label :vehicle_number %><br>
                    <%= form.text_field :vehicle_number , class: "form-control form-control-lg"%>
                  </div>

                  <div class="mt-2">
                    <%= form.label :Contact%><br>
                    <%= form.text_field :contact_number , class: "form-control form-control-lg"%>
                  </div>

                  <div class="mt-2">
                    <%= form.label :Category %><br>
                    <%= form.text_field :category , class: "form-control form-control-lg"%>
                  </div>


                  <div class="mt-2">
                    <%= form.label :Cost %><br>
                    <%= form.text_field :cost , class: "form-control form-control-lg"%>
                  </div>
                  

                  <div class="mt-2">
                    <%= form.label :Request_time %><br>
                    <%= form.text_field :request_time, class: "form-control form-control-lg"%>
                  </div>

                  <div class="mt-2">
                    <%= form.label :request_date%><br>
                    <%= form.text_field :request_date, class: "form-control form-control-lg"%>
                  </div>

                  <div class="mt-2">
                    <%= form.label :confirm_time%><br>
                    <%= form.text_field :confirm_time, class: "form-control form-control-lg"%>
                  </div>


                  <div class="mt-2">
                    <%= form.label :confirm_date%><br>
                    <%= form.text_field :confirm_date, class: "form-control form-control-lg"%>
                  </div>


                  <div class="mt-2">
                    <%= form.label :alloted_slot%><br>
                    <%= form.text_field :alloted_slot, class: "form-control form-control-lg"%>
                  </div>

            
                  <div class="mt-2">
                    <%= form.label :another_request_time%><br>
                    <%= form.text_field :another_request_time, class: "form-control form-control-lg"%>
                  </div>


                  <div class="mt-2">
                    <%= form.hidden_field :service_center_id, class: "form-control form-control-lg"%>
                  </div>
                   
                  <div class="text-center mt-3">
                    <%= form.submit %>
                  </div>

                  <%end%>
                  <div style="margin-top: -36px;">
                    <%= link_to "Cancel",order_cancel_path(i.id,i.service_center_id), class:"btn btn-danger"%>
                  </div>


        </div>
      </div>



      <!-- <%= link_to "confirm" ,order_confirmation_path(i.id), class: 'btn-primary'%> -->
      <!-- <%= link_to 'Click', show_data_client_path(i.id) ,class: 'btn btn-primary' %> -->
      <%end%>
        <%else%>
          <h1>Having nothing to display</h1>
          <%end%>

</div>

app/views/service_centers/service_type.html.erb
<%= form_with method: :get,url:add_service_path(@id) do |form| %>
  <div>
    <%= form.label :Service_Name %><br>
    <%= form.text_field :service_name %>
  </div>

  <div>
    <%= form.label :Cost_of_service%><br>
    <%= form.text_field :service_cost %>
  </div>
 
  <div>
    <%= form.submit %>
  </div>
<% end %> 

app/views/service_centers/shop_detail.html.erb
 <%= flash[:n]%>

<div class="container add">
        <div class="row">
                  <div class="col-3">

                    <% if @shop %>
           
    <% @shop.each do |i|%>
    <%=i.shop_name%> <br>
    <%=i.shop_owner%> <br>
    <%=i.location%> <br>
    <%=i.address%> <br>
    <% a = ServiceCenter.find(i.id)%>
             <% a.slots.all.each do |j|%>
              <%=j.name%> 
              <%=j.status%><br>
             <%end%>

    
    
    
    
    <%= form_with method: :get,url:add_service_path(i.id) do |form| %>
       
    <div class="form-group mb-2">
      <%= form.label :category%><br>
       <%= form.collection_select :category,CategoryList.all,:name ,:name%>
      </div>
  
      <div>
        <%= form.submit %>
      </div>
    <% end %> 
    
    
    
     
    
    <%= form_with method: :post ,url: { controller: 'slot', action: 'create', id: i.id } do |form| %>
      <div>
        <%= form.label :Slot_Name %><br>
        <%= form.text_field :name %>
      </div> 
      <div>
        <%= form.submit 'add'%>
      </div>
    <% end %> 
    
    
    
    <p>-------------------------------------------------------------------------</p>
    <%end%>
    

       <%else%>
       Nothing having to display
  <%end%>


                  </div>

                  <div class="col-8">
                     
                      
                    
                     

                      <table class="table table-hover">
                        <thead>
                          <tr>
                            
                            <th scope="col">category</th>
                            <th scope="col">Time</th>
                            <th scope="col">Price</th>
                          </tr>
                        </thead>
                        <tbody>
                          <%@category.each do |i|%>
                          <tr>
                            
                            <td>  <%=i.name%> </td>
                            <td>  <%=i.time%> </td>
                            <td>  <%=i.cost%></td>
                          </tr>
                          <%end%>
                      
                        
                        </tbody>
                      </table>
                  </div>

        </div>
           
</div>

app/views/service_centers/show.html.erb
<%if @request_id %>
<h1>Thank you for requesting to <%= @request_id.shop_name%></h1>
<%else%>
No name to displya yet
<%end%>

app/views/service_centers/show_data.html.erb
      
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">  Shop_name:</th>
            <th scope="col">  Shop_name: </th>
            <th scope="col">  Location </th>
            <th scope="col">  Address</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @a.shop_owner%></td>
            <td><%= @a.shop_name%></td>
            <td><%= @a.location%></td>
            <td><%= @a.address%></td>
          </tr>
      
        </tbody>
      </table>



     
     
    
     
    

app/views/service_centers/update.html.erb
sdfg