config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :user_crud
  resources :category_list
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  root to: 'service_centers#index'
  resources :service_centers do
    collection do
      get 'shop_detail', to: 'service_centers#shop_detail'
      get 'admin', to: 'service_centers#admin'    
      get 'all_shop', to: "service_centers#all_shop"
      get 'shop_list', to: "service_centers#shop_list"
      post "order_pending", to: "service_centers#order_pending"
    end    
    member do
      get 'show_data', to: "service_centers#show_data"
      get 'update_to', to: "service_centers#update_to"
    end
  end
  get 'order/:id/:service_id',to: "clients#order_cancel",as: :order_cancel
  get 'client_request/:id', to: 'service_centers#client_request',as: :client_request
  get 'add_service/:id', to: 'service_centers#add_service', as: :add_service
  get 'request_to_owner/:id', to:'service_centers#request_to_owner',as: :request_to_owner
  post 'order_confirmation/:data/' , to: 'service_centers#order_confirmation',as: :order_confirmation
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  get 'payment/:client_id/:cost/:service_center_id', to: 'service_centers#payment', as: 'payment'
  post 'charge', to: 'service_centers#charge', as: 'charge'
  # root "articles#index"
  resources :clients do
    collection do  
      get "user_profile",to: 'clients#user_profile'
      get "admin_path" ,to: "clients#admin"
    end    
    member do 
      get "show_data", to: "clients#show_data"
      get "update_slot", to: "clients#update_slot"
      get "bill_detail", to: "clients#bill_detail"
      get 'revenue',to: "clients#revenue"
    end  

  end
  resources :slot ,except: %i[create edit destroy]
  post 'create/:id', to: 'slot#create'
  get 'edit/:service_id/:slot_id',to: 'slot#edit' ,as: :edit_slot
  get 'delete/:service_id/:slot_id',to: 'slot#edit' ,as: :delete_slot
end

app/models/slot.rb
class Slot < ApplicationRecord
    scope :available, -> { where(:status => 'available')}
    scope :available?, -> { where(:status => 'available')}

    # Ex:- scope :active, -> {where(:active => true)}
end

app/controllers/slot_controller.rb
class SlotController < ApplicationController
  include Vehicle
  def index
  end

  def show
    @service = ServiceCenter.find(params[:id])
    @slot = @service.slots.all
  end

  def edit
    @service = ServiceCenter.find(params[:service_id])
    @ed = @service.slots.find(params[:slot_id]) 
  end
 
  def update
    @edit = Slot.find(params[:id])
    @edit.update(slot_params)
  end

  def destroy
    @service = ServiceCenter.find(params[:service_id])
    @delete = @service.slots.find(params[:slot_id])
    @delete.destroy
  end
  

  def create
    slot_association(params)
    flash[:n] = "Slot add successfully"
    redirect_to shop_detail_service_centers_path
  end

  private
  def slot_params
      params.require(:slot).permit(:name,:status)
  end 

end

app/helpers/slot_helper.rb
module SlotHelper
end

app/views/slot/create.html.erb
<h1>Slot#create</h1>
<p>Find me in app/views/slot/create.html.erb</p>

app/views/slot/edit.html.erb
<div class="container add mt-4">

    <%= form_with model:@ed do |form| %>
    <div>
        <%= form.label :name %><br>
        <%= form.text_field :name%>
      </div>
    <div>
      <%= form.label :status%><br>
      <%= form.text_field :status%>
    </div>


    <div>
      <%= form.submit%>
    </div>
<% end %> 



 </div>

app/views/slot/index.html.erb
<h1>Slot#index</h1>
<p>Find me in app/views/slot/index.html.erb</p>

app/views/slot/show.html.erb
<div class="bg">

    <h2>Slot Table</h2>
    
    
    <div class="table-wrapper">
        <table class="fl-table">
            <thead>
            <tr>
                <th>Name</th>
                <th>Status</th>
                <th>Show</th>
                <th>Edit</th>
                <th>Destroy</th>
    
            </tr>
            </thead>
            <tbody>
        
                <% @slot.each do |i|%>
            <tr>
                <td> <%=i.name%></td>
                <td> <%=i.status%></td>
                <td> <%=link_to "Show",show_data_service_center_path(i.id),class:"btn btn-danger"%> </td>
                <td>  <%=link_to "Edit",edit_slot_path(i.service_center_id,i.id),class:"btn btn-danger"%></td>
                <td> <%= link_to "Destroy", delete_slot_path(i.service_center_id,i.id),class:"btn btn-danger",data: {turbo_method: :delete,turbo_confirm: "Are you sure?"} %></td>
            </tr>
            <%end%>
           
            <tbody>
        </table>
    </div>
    
      </div>

app/views/slot/update.html.erb
<h1>Slot#update</h1>
<p>Find me in app/views/slot/update.html.erb</p>