config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :user_crud
  resources :category_list
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  root to: 'service_centers#index'
  resources :service_centers do
    collection do
      get 'shop_detail', to: 'service_centers#shop_detail'
      get 'admin', to: 'service_centers#admin'    
      get 'all_shop', to: "service_centers#all_shop"
      get 'shop_list', to: "service_centers#shop_list"
      post "order_pending", to: "service_centers#order_pending"
    end    
    member do
      get 'show_data', to: "service_centers#show_data"
      get 'update_to', to: "service_centers#update_to"
    end
  end
  get 'order/:id/:service_id',to: "clients#order_cancel",as: :order_cancel
  get 'client_request/:id', to: 'service_centers#client_request',as: :client_request
  get 'add_service/:id', to: 'service_centers#add_service', as: :add_service
  get 'request_to_owner/:id', to:'service_centers#request_to_owner',as: :request_to_owner
  post 'order_confirmation/:data/' , to: 'service_centers#order_confirmation',as: :order_confirmation
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  get 'payment/:client_id/:cost/:service_center_id', to: 'service_centers#payment', as: 'payment'
  post 'charge', to: 'service_centers#charge', as: 'charge'
  # root "articles#index"
  resources :clients do
    collection do  
      get "user_profile",to: 'clients#user_profile'
      get "admin_path" ,to: "clients#admin"
    end    
    member do 
      get "show_data", to: "clients#show_data"
      get "update_slot", to: "clients#update_slot"
      get "bill_detail", to: "clients#bill_detail"
      get 'revenue',to: "clients#revenue"
    end  

  end
  resources :slot ,except: %i[create edit destroy]
  post 'create/:id', to: 'slot#create'
  get 'edit/:service_id/:slot_id',to: 'slot#edit' ,as: :edit_slot
  get 'delete/:service_id/:slot_id',to: 'slot#edit' ,as: :delete_slot
end

app/models/category_list.rb
class CategoryList < ApplicationRecord
    scope :cat, -> { where(:status => 'available')}
end

app/controllers/category_list_controller.rb
class CategoryListController < ApplicationController
  def index
    authorize! :read, CategoryList
    @all = CategoryList.all
  end

  def create
    authorize! :create, CategoryList
    @admin = CategoryList.new(category_params)
    if @admin.save
      flash[:n] = "Succefully updated"
      redirect_to category_list_index_path
    end   
  end

  def update
    a = CategoryList.find(params[:id])
    a.update(category_params)
  end

  def show
    authorize! :read, CategoryList
    @show = CategoryList.find(params[:id])
  end

  def new
    authorize! :read, CategoryList
    @admin = CategoryList.new 
  end

  def edit
    authorize! :read, CategoryList
    @list = CategoryList.find(params[:id])
  end

  def destroy
    authorize! :read, CategoryList
    @d=CategoryList.find(params[:id])
    @d.destroy
  end

  private
  def category_params
    params.require(:category_list).permit(:name,:cost,:time)
  end   
end

app/helpers/category_list_helper.rb
module CategoryListHelper
end

app/views/category_list/create.html.erb
<h1>CategoryList#create</h1>
<p>Find me in app/views/category_list/create.html.erb</p>

app/views/category_list/destroy.html.erb
<h1>CategoryList#destroy</h1>
<p>Find me in app/views/category_list/destroy.html.erb</p>

app/views/category_list/edit.html.erb
<div class="container add mt-4">

    <%= form_with model:@list do |form| %>
    <div>
      <%= form.label :Category_list%><br>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :Price %><br>
      <%= form.text_field :cost%>
    </div>

    <div>
      <%= form.label :Time %><br>
      <%= form.text_field :time%>
    </div>
    
    <div>
      <%= form.submit%>
    </div>
<% end %> 



 </div>

app/views/category_list/index.html.erb
  <!-- 
 <div class="container add">


    <% @all.each do |i|%>
    <%=i.name%>
    <%=i.cost%>
    <%=i.time%> 
    <%=link_to "carete",new_category_list_path,class:"btn btn-danger"%>
    <%=link_to "show",category_list_path(i),class:"btn btn-danger"%>
    <%=link_to "edit", edit_category_list_path(i),class:"btn btn-danger"%>
    <%= link_to "Destroy", category_list_path(i), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %>
    <%end%>



 </div> -->


  <div class="bg">

<h2>Category Table <%=link_to "carete",new_category_list_path,class:"btn btn-danger text-center"%></h2>


<div class="table-wrapper">
    <table class="fl-table">
        <thead>
        <tr>
            <th>Name</th>
            <th>cost</th>
            <th>Time</th>
            <th>Show</th>
            <th>Edit</th>
            <th>Destroy</th>

        </tr>
        </thead>
        <tbody>
    
        <% @all.each do |i|%>
        <tr>
            <td> <%=i.name%></td>
            <td> <%=i.cost%></td>
            <td> <%=i.time%></td>
            <td> <%=link_to "show",category_list_path(i),class:"btn btn-danger"%> </td>
            <td> <%=link_to "edit", edit_category_list_path(i),class:"btn btn-danger"%></td>
            <td> <%= link_to "Destroy", category_list_path(i), data: {turbo_method: :delete,turbo_confirm: "Are you sure?" } %></td>
        </tr>
        <%end%>
       
        <tbody>
    </table>
</div>

  </div>

app/views/category_list/new.html.erb
<%=flash[:n]%>
<div class="container add mt-4">

    <%= form_with method: :post ,model:@admin, url: {controller: 'category_list', action: 'create'} do |form| %>
    <div>
      <%= form.label :Category_list%><br>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :Price %><br>
      <%= form.text_field :cost%>
    </div>

    <div>
      <%= form.label :Time %><br>
      <%= form.text_field :time%>
    </div>
    
    <div>
      <%= form.submit "Create list"%>
    </div>
<% end %> 



 </div>

app/views/category_list/show.html.erb
<%=@show.name%>

app/views/category_list/update.html.erb
<h1>CategoryList#update</h1>
<p>Find me in app/views/category_list/update.html.erb</p>